name: GitHub Actions Test
run-name: 0.1-{{ github.run_number }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test"
  deployment:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo "Deployed to test"
